export function ChipTitleBottom({ title }){
 return(
  <span
   className="
    font-itclight
    absolute
    text-sm
    px-3
    py-1.5
    bg-neutral-100
    rounded-full
    outline-2
    outline-[#d9dbe9]
    w-fit
    bottom-4
    left-4
    text-neutral-700
    transition-colors
    duration-colors
    group-hover:text-neutral-100
    group-hover:bg-black
    transition-colors
    duration-300
   ">
   {title}
  </span>
 );
}